version: '3.8'

services:
  radicale:
    build: .
    ports:
      - "5232:5232"
    volumes:
      - ./data:/data
      - ./config:/etc/radicale/config
      - ./users:/data/users
    environment:
      - RADICALE_CONFIG=/etc/radicale/config
    restart: unless-stopped
    init: true
    read_only: false
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - KILL
    pids_limit: 50
    mem_limit: 256M
    healthcheck:
      test: [ "CMD", "/venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5232/.well-known/caldav')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - radicale_network

networks:
  radicale_network:
    driver: bridge
    enable_ipv6: true
